name: CI/CD for genai-health-data-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:  
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Miniconda
        uses: s-weigand/setup-conda@v1

      # Run the setup.sh script which will create conda environment and install dependencies
      - name: Run setup script
        run: |
          chmod +x setup.sh
          bash setup.sh
       
      - name: Verify installation
        run: |
          conda activate genai-env
