name: CI/CD for genai-health-data-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:  
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda and install dependecies with setup.sh
        run: |
          chmod +x setup.sh
          ./install.sh

      - name: Verify installation
        run: |
          conda activate genai-env
